### ISSUE TITLE
Add method to start / stop spinning wheel dynamically

### ISSUE THREAD

**Issue by nambv** [davidanaya/flutter-spinning-wheel#1]
Your library is very awesome!

Can you add some custom methods that allow to start / stop the wheel from the outside, such as click a button to handle it?

**Comment by davidanaya** [comment]
Thanks @nambv 
I could do that, but what do you have in mind specifically?
start -- starts the wheel at what speed? random? or does it spins the wheel indefinitely?
stop -- stops the wheel immediately? or just decelerates it?
in this case, do you want the user to be able to interact with the wheel through gestures?

**Comment by nambv** [comment]
Hi @davidanaya , thank you very much for reply to my issue.

1. I think we can start the wheel with specified speed.
2. Decelerates is better, so I prefer it.
3. In this case, we shouldn't allow user to be able to interact with the wheel through gestures

**Comment by davidanaya** [comment]
@nambv I added a Stream to communicate with the inner widget.
You can see how I use it to trigger the start of the animation in the example for the roulette
https://github.com/davidanaya/flutter-spinning-wheel/blob/master/example/lib/main.dart

You need to provide a double as velocity which roughly goes from 1000 (barely noticeable) to 10000 pixels per second. In the example I generate a random velocity each time and it works pretty well.
`double _generateRandomVelocity() => (Random().nextDouble() * 6000) + 2000;`

**Comment by nambv** [comment]
@davidanaya thanks alot! 👍 I will take a look!

**Comment by davidanaya** [comment]
Closing the issue as last reply is a month ago.

**Comment by Renatinaveen** [comment]
@davidanaya @nambv is it possible to control the stopping point when the animation ends? i want to control where the animation stops.
